name: Playwright Tests - PROD
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  setup-and-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        shard: [1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8, 8/8]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --shard ${{matrix.shard}}
      env:
        TESTUSER_USERNAME: ${{ secrets.TESTUSER_USERNAME }}
        TESTUSER_PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
        TOKEN_URL: ${{ secrets.TOKEN_URL }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-allure
        path: allure-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blob-report
        path: blob-report/
        retention-days: 30
  
  merge-reports:
    if: always()
    needs: [setup-and-run]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        name: blob-report
        path: blob-report
    
    - name: Merge into HTML report
      run: npx playwright merge-reports --reporter html ./blob-report

    - name: Upload HTML report
      uses: actions/checkout@v4
      with:
        name: html-report--attempt-${{github.run_attempt}}
        path: playwright-report
        retention-days: 30